# Generated by Django 3.0.8 on 2020-08-08 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='权限名称')),
                ('url', models.CharField(blank=True, max_length=256, null=True, verbose_name='权限的url')),
                ('is_menu', models.BooleanField(default=False, verbose_name='是否是菜单')),
                ('icon', models.CharField(blank=True, max_length=32, null=True, verbose_name='权限图标')),
                ('parent_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Permission', verbose_name='父菜单')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='角色名称')),
                ('permission', models.ManyToManyField(blank=True, to='app01.Permission', verbose_name='角色的权限')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(blank=True, to='app01.Role', verbose_name='用户的角色'),
        ),
    ]
