# Generated by Django 3.0.8 on 2020-08-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20200808_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(blank=True, null=True, to='app01.Role', verbose_name='用户的角色'),
        ),
    ]
