# Generated by Django 3.0.8 on 2020-08-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20200808_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='alias',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='权限别名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(blank=True, to='app01.Role', verbose_name='用户的角色'),
        ),
    ]
