# Generated by Django 3.0.8 on 2020-08-09 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20200809_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='主机名称')),
                ('ip', models.GenericIPAddressField(verbose_name='主机IP')),
                ('username', models.CharField(max_length=64, verbose_name='主机账户')),
                ('password', models.CharField(max_length=32, verbose_name='主机密码')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='主机信息更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='主机的拥有者')),
            ],
            options={
                'verbose_name': '主机',
                'verbose_name_plural': '主机',
            },
        ),
    ]
