# Generated by Django 2.1.10 on 2020-07-18 14:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='贴子标题')),
                ('slug', models.CharField(max_length=200, verbose_name='贴子摘要')),
                ('body', models.TextField(verbose_name='贴子内容')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2020, 7, 18, 14, 48, 20, 605129, tzinfo=utc), verbose_name='贴子的发表时间')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
